services:
  - type: web
    name: meetfit-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: true
      - key: MONGODB_URI
        sync: true
      - key: JWT_SECRET
        sync: true
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: UPLOAD_PATH
        value: uploads/
      - key: MAX_FILE_SIZE
        value: 5000000